version: '3.8'

services:

  mongo:
    container_name: mongo
    image: mongo:4.4.15
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "27017:27017"
    volumes:
      - ./mongoDb:/data/db
    environment:
      MONGO_INITDB_DATABAS: $MONGODB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD